name: Build and Push Docker data speech Image

on:
  push:
    paths:
      - requirements.txt
      - Dockerfile.speech
    branches:
      - main
  pull_request:
    paths:
      - requirements.txt
      - Dockerfile.speech
    branches:
      - main  # Only run for pull requests targeting main
  workflow_dispatch:  # Allows manual triggering of the workflow

env:
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/data_speech
  IMAGE_TAG: ${{ github.sha }}  # Tag the image with the commit SHA
  MAIN_BRANCH: main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker image
        run: docker build --file Dockerfile.speech --tag ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: docker push ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: Tag image as latest if on main branch
        if: github.ref == 'refs/heads/${{ env.MAIN_BRANCH }}'
        run: |
          docker tag ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} ${{ env.IMAGE_NAME }}:latest
          docker push ${{ env.IMAGE_NAME }}:latest
