name: Build and Push Speech Data Processing Image

on:
  push:
    paths:
      - requirements.txt
      - Dockerfile.speech
    branches:
      - main
  pull_request:
    paths:
      - requirements.txt
      - Dockerfile.speech
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering of the workflow

env:
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/forb-speech-data-processor
  IMAGE_TAG: ${{ github.sha }}  # Tag the image with the commit SHA
  MAIN_BRANCH: main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-speech-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-speech-
            
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}
            
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.speech
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          build-args: |
            PYTHON_VERSION=3.10
            
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
          
      - name: Image digest
        run: echo ${{ steps.build.outputs.digest }}
        
      - name: Verify image
        run: |
          docker run --rm ${{ env.IMAGE_NAME }}:${{ github.sha }} python --version
          docker run --rm ${{ env.IMAGE_NAME }}:${{ github.sha }} pip list | grep -E "(torch|librosa|soundfile|datasets)"
